# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "2.7"

before_install:
    - pip install numpy
    - pip install -r requirements-dev.txt

install:
    - python setup.py install
    - pip install codecov

script:
    - nosetests -v --with-coverage align/tests

after_success:
    - codecov
